# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-rc.2-jammy AS build
ARG TARGETARCH
WORKDIR /src
COPY . .
RUN apt-get update && apt-get install -y clang zlib1g-dev build-essential
RUN dotnet restore
RUN dotnet publish -a $TARGETARCH --no-restore -c Release -o /publish --sc -v d


# Final Image
FROM mcr.microsoft.com/dotnet/runtime-deps:8.0-jammy-chiseled
WORKDIR /app
COPY --from=build /publish/MatchFunction ./
ENTRYPOINT ["./MatchFunction"]