FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG TARGETARCH
WORKDIR /source

# Additional packages needed for AOT
RUN apk add --no-cache --upgrade clang build-base zlib-dev
# copy csproj and restore as distinct layers
COPY ["GameFrontend.csproj", "./"]
RUN dotnet restore "GameFrontend.csproj" -a $TARGETARCH

# copy everything else and build app
COPY . .
WORKDIR "/src/src/GameFrontend"
RUN dotnet publish -a $TARGETARCH --self-contained false --no-restore -o /app


# To enable globalization:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md
# final stage/image
# .NET 8 tag includes `-preview`
FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine

# These ENVs are only needed because the sample uses .NET 7
ENV DOTNET_ROLL_FORWARD=Major
ENV DOTNET_ROLL_FORWARD_PRE_RELEASE=1

WORKDIR /app
COPY --from=build /app .

USER $APP_UID
ENTRYPOINT ["./aspnetapp"]